$ErrorActionPreference='Stop'
$d='D:\Project\厚粲杯\11_数据'; $out='D:\Project\厚粲杯\08_算法\docs\results\final_merge_readiness_20260829'; New-Item -ItemType Directory -Force $out | Out-Null
$a=Import-Csv "$d\derived\focuswave_canonical_v1_rerun_20260826\focuswave_canonical_v1\beijing-nvidia-main\report_cohort_v1\merge_ready\report_analysis_cohort.csv"
$m=Import-Csv "$d\derived\focuswave_canonical_v1_rerun_20260826\focuswave_canonical_v1\beijing-nvidia-main\mmwave_m1_v1\merge_ready\m1_q0_probe_matrix.csv"
$r=Import-Csv "$d\04_Attention-Analysis_nvidia-cuda_RGB\cohort_status.csv"; $n=Import-Csv "$d\derived\nir_69session_final_probe_analysis_v1\nir_session_qc_summary.csv"
$mm=@{}; foreach($x in $m){$mm["$($x.subject.PadLeft(3,'0'))|$($x.probe_id)"]=$x}; $rgb=@{}; foreach($x in $r){$rgb[$x.subject]=$x}; $nir=@{}; foreach($x in $n){$nir[$x.subject]=$x}
$s=@(); $p=@()
foreach($g in ($a|Group-Object session_id)){ $f=$g.Group[0]; $sub='sub-'+$f.subject_id.ToString().PadLeft(3,'0'); $sid=$f.session_id; $rp=$f.repeat_participant_id; $mx=@($m|?{('sub-'+$_.subject.PadLeft(3,'0')) -eq $sub}); $ok=@($mx|?{$_.quality -eq 'ok' -and $_.q_extraction_ok -eq '1.0'}); $ra=$null -ne $rgb[$sub] -and $rgb[$sub].status -in @('complete','skipped_complete'); $na=$nir.ContainsKey($sub); $s += [pscustomobject]@{subject=$sub;session=$sid;repeat_participant_id=$rp;behavior_available='yes';probe_available='yes';mmwave_available=($(if($mx.Count){'yes'}else{'no'}));mmwave_qc_class=($(if($ok.Count){'formal_qc_v1_probe_pass_available'}else{'missing_or_no_qc_pass'}));rgb_available=($(if($ra){'yes'}else{'no'}));rgb_qc_class=($(if($ra){'engineering_complete_formal_analysis_not_authorized'}else{'missing'}));nir_available=($(if($na){'yes'}else{'no'}));nir_qc_class=($(if($na){'completion_present_probe_alignment_not_recomputed'}else{'not_completion_in_canonical_cohort'}));usable_behavior_baseline='yes';usable_behavior_rgb=($(if($ra){'yes'}else{'no'}));usable_behavior_mmwave=($(if($ok.Count){'yes'}else{'no'}));usable_behavior_rgb_mmwave=($(if($ra -and $ok.Count){'yes'}else{'no'}));usable_full_multimodal=($(if($ra -and $ok.Count -and $na){'yes'}else{'no'}));exclusion_reason=($(if($ra -and $ok.Count -and $na){''}else{'modality_missing_or_not_formally_authorized'}))}; foreach($x in $g.Group){$z=$mm["$($x.subject_id.ToString().PadLeft(3,'0'))|$($x.session_probe_index)"]; $pass=$null -ne $z -and $z.quality -eq 'ok' -and $z.q_extraction_ok -eq '1.0'; $p += [pscustomobject]@{subject=$sub;session=$sid;repeat_participant_id=$rp;probe_id=$x.session_probe_index;behavior_available='yes';probe_available='yes';mmwave_available=($(if($null -ne $z){'yes'}else{'no'}));mmwave_qc_class=($(if($pass){'formal_qc_v1_pass'}elseif($null -ne $z){'formal_qc_v1_present_not_pass'}else{'missing'}));rgb_available=($(if($ra){'yes'}else{'no'}));rgb_qc_class=($(if($ra){'engineering_complete_formal_analysis_not_authorized'}else{'missing'}));nir_available=($(if($na){'yes'}else{'no'}));nir_qc_class=($(if($na){'completion_present_probe_alignment_not_recomputed'}else{'not_completion_in_canonical_cohort'}));usable_behavior_baseline='yes';usable_behavior_rgb=($(if($ra){'yes'}else{'no'}));usable_behavior_mmwave=($(if($pass){'yes'}else{'no'}));usable_behavior_rgb_mmwave=($(if($ra -and $pass){'yes'}else{'no'}));usable_full_multimodal=($(if($ra -and $pass -and $na){'yes'}else{'no'}));exclusion_reason=($(if($ra -and $pass -and $na){''}else{'modality_missing_or_not_formally_authorized'}))} } }
$s|Sort-Object subject|Export-Csv "$out\merge_session_availability_matrix.csv" -NoTypeInformation -Encoding UTF8; $p|Sort-Object subject,probe_id|Export-Csv "$out\merge_probe_level_availability_matrix.csv" -NoTypeInformation -Encoding UTF8
$sets=@([pscustomobject]@{model_set='A_behavior_probe_baseline';level='primary';n_session=70;n_participant=46;n_probe=1400;status='available_canonical';qc_boundary='behavior/probe canonical anchor'},[pscustomobject]@{model_set='B_behavior_plus_RGB';level='incremental';n_session=70;n_participant=46;n_probe=1400;status='available_input_engineering_only';qc_boundary='RGB formal gate pending'},[pscustomobject]@{model_set='C_behavior_plus_mmWave_usable';level='incremental';n_session=70;n_participant=46;n_probe=$p|? usable_behavior_mmwave -eq 'yes'|measure|% Count;status='available_qc_subset';qc_boundary='formal QC v1 pass probes only'},[pscustomobject]@{model_set='D_behavior_plus_RGB_plus_mmWave';level='auxiliary';n_session=70;n_participant=46;n_probe=$p|? usable_behavior_rgb_mmwave -eq 'yes'|measure|% Count;status='available_matched_qc_subset';qc_boundary='RGB engineering plus mmWave QC pass'},[pscustomobject]@{model_set='E_behavior_plus_RGB_plus_mmWave_plus_NIR';level='NIR_subsample_validation';n_session=$s|? usable_full_multimodal -eq 'yes'|measure|% Count;n_participant=($s|? usable_full_multimodal -eq 'yes'|group repeat_participant_id|measure|% Count);n_probe=$p|? usable_full_multimodal -eq 'yes'|measure|% Count;status='completion_subjects_only';qc_boundary='NIR completion and alignment gate'}); $sets|Export-Csv "$out\available_model_sets.csv" -NoTypeInformation -Encoding UTF8
$mmok=$p|? usable_behavior_mmwave -eq 'yes'|measure|% Count; $nirp=$p|? nir_available -eq 'yes'|measure|% Count; $mods=@([pscustomobject]@{modality='behavior';denominator='canonical cohort';session_available=70;session_total=70;session_missing=0;probe_available=1400;probe_total=1400;probe_missing=0;status='canonical'},[pscustomobject]@{modality='probe';denominator='canonical cohort';session_available=70;session_total=70;session_missing=0;probe_available=1400;probe_total=1400;probe_missing=0;status='canonical'},[pscustomobject]@{modality='mmWave';denominator='canonical cohort';session_available=70;session_total=70;session_missing=0;probe_available=$mmok;probe_total=1400;probe_missing=1400-$mmok;status='formal QC v1 subset; un-QC excluded'},[pscustomobject]@{modality='RGB';denominator='canonical cohort';session_available=70;session_total=70;session_missing=0;probe_available=1400;probe_total=1400;probe_missing=0;status='engineering complete; formal authorization pending'},[pscustomobject]@{modality='NIR';denominator='canonical cohort';session_available=$s|? nir_available -eq 'yes'|measure|% Count;session_total=70;session_missing=70-($s|? nir_available -eq 'yes'|measure|% Count);probe_available=$nirp;probe_total=1400;probe_missing=1400-$nirp;status='completion subjects only'}); $mods|Export-Csv "$out\missingness_by_modality.csv" -NoTypeInformation -Encoding UTF8


